name: Q4

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  archive-q4:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Créer Q4_archive
        run: |
          DATE=$(date '+%d-%m-%Y')
          FILENAME="Q4_archive_${DATE}.txt"
          echo "Lucas Langlois" > $FILENAME
          echo "Contenu de Q4.java :" >> $FILENAME
          cat Q4.java >> $FILENAME

      - name: Configurer Git
        run: |
          git config user.name "LucasLgLsGit"
          git config user.email "lucas.langlois1@etu.univ-lehavre.fr"

      - name: Commit et push du fichier archivé
        run: |
          DATE=$(date '+%d-%m-%Y')
          FILENAME="Q4_archive_${DATE}.txt"
          git add $FILENAME
          git commit -m "Q4.java avec date dans le nom"
          git push
